### ISSUE TITLE
Autoregister sphinx.ext.autodoc when autodoc_traits is registered as a sphinx extension?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/autodoc-traits#12]
In [this sphinx example](https://www.sphinx-doc.org/en/master/development/tutorials/autodoc_ext.html#writing-the-extension) on how to write an extension for sphinx.ext.autodoc, they register the sphinx.ext.autodoc extension in the extension itself like this:

```python
def setup(app: Sphinx) -> None:
    app.setup_extension('sphinx.ext.autodoc')  # Require autodoc extension
    app.add_autodocumenter(IntEnumDocumenter)
```

Should we do the same in this extension? That would make someone able to just add `autodoc_traits` as a sphinx extensions in their sphinx conf.py file.

https://github.com/jupyterhub/autodoc-traits/blob/d618d9e57023b00575436a0928c231e7e779bfe3/autodoc_traits/autodoc_traits.py#L60-L62

**Comment by minrk** [comment]
Yes, I think that makes sense!
