### ISSUE TITLE
autoclass finds traits, but doesn't find their docstrings

### ISSUE THREAD

**Issue by minrk** [jupyterhub/autodoc-traits#30]
### Bug description

When using autoclass (not autoconfigurable), traits with help strings are treated as undocumented. That means they are excluded from `:members:`, but included with `:undoc-members:`. When they are included with `:undoc-members:`, they are all represented with their _class_ docstring instead of their help string, like:

#### Expected behaviour

members/undoc-members should recognize the `help` string of traitlets as being documented, and be included/excluded accordingly.

#### Actual behaviour

all traits are treated as undocumented members, help strings are not extracted, and all traits are represented as configurable, even when they are not.

### How to reproduce

```rst
..  autoclass:: test_module.TestConfigurable
   :noindex:
   :members:
   # :undoc-members:
```

produces output like

```python
    trait_noconfig = Bool(
        help="""trait_noconfig help text""",
    )
```

into

```
trait_noconfig c.SampleConfigurable.trait_noconfig = Bool(False)
    A boolean (True, False) trait.
```

Note:

- help string is wrong
- formatting is for a config trait, which is also wrong

### More info

Issue prompted by https://github.com/jupyterhub/autodoc-traits/pull/28#discussion_r1048438152

This is a low priority issue, since most things should use `autoconfigurable`, which does this right. But good general autoclass support for HasTraits would be nice, if possible.

**Comment by consideRatio** [comment]
I looked to accomplish support for autoclass to render things better with autodoc_traits installed, but it was hard to influence that. The thing is that if you use the autoclass directive, you get the original sphinx directive and have little control of it.

If you choose to use the `automodule` directive, it will list members based on other directives that is listed with priority to be able to handle `class` type members. And then, autoconfigurable will be chosen over autoclass to document a module's class members if it has traits.

Similarly, a class can have members, and they can be documented. But, they are exlucded before that is considered. In autoconfigurable, this is hacked by adding a `__doc__` field for traits.

If we replace the strategy used in autoconfigurable, to add `__doc__` to traitlet objects, at some other time before `autoclass` does its logic - we would get `autoclass` to respect the traitlet attributes as functions and other stuff.

## Summary

```rst
# ModuleDocumenter provides `automodule`, so it will be used.
# This documenter has members of class type, so either ClassDocumenter
# or ConfigurableDocumenter could be used to document individual class
# members of the module.
#
# ConfigurableDocumenter will say it can't document the class
# if it doesn't have traitlets members. If it does, it will say it has a higher priority than
# ClassDocumenter.
.. automodule:: sample_module

# ClassDocumenter provides `autoclass`, so it will be used.
# This documenter has members of attribute type, so either AttributeDocumenter or
# TraitDocumenter could be used to document individual attribute members of the class.
#
# TraitDocumenter will say it can't document the attribute if it isn't of a traitlets type, but
# will report a higher priority than AttributeDocumenter if it is of traitlets type.
#
# Certain logic related to `autoclass` will make traitlet members be filtered out as they
# lack `__doc__`. This logic is part of the base class Documenter.
#
.. autoclass:: sample_module.SampleConfigurable

# ConfigurableDocumenter provides `autoconfigurable`, so it will be used.
# This documenter has members of attribute type, so either AttributeDocumenter or
# TraitDocumenter could be used to document individual attribute members of the class.
#
# TraitDocumenter will say it can't document the attribute if it isn't of a traitlets type, but
# will report a higher priority than AttributeDocumenter if it is of traitlets type.
#
# Certain logic related to `autoconfigurable` will make traitlet members be filtered out as they
# lack `__doc__`. This logic is part of the base class Documenter. A hack is used to workaround
# this though. When ConfigurableDocumenter's `get_object_members` obverride is called, it will
# patch __doc__ and provide a dummy truthy string, making it not be filtered out without influencing
# the base class filtering system, but instead helping it to do the right thing.
#
.. autoconfigurable:: sample_module.SampleConfigurable
```

I think if you have both `.. autoconfigurable:: sample_module.SampleConfigurable` and `.. autoclass:: sample_module.SampleConfigurable`, you may end up with `autoclass` behavior changed as objects has been patched.

Maybe the best strategy would be to patch __doc__ for traitlets even before, or patch the common filtering functionality. I don't think we can replace the filtering functionality in the base class though, its too intertwined in other logic. Maybe we can register to some event or similar to apply the patch, adding __doc__ to all traits though.

Its quite messy overall. A big deal for anyone working on this would be if a desired outcome is clearly defined. How should `autoclass` behave? Exactly like `autoconfigrable`, or just able to render members like autoconfigurable but not render trait members unless `:members:` or similar is specified?
