### ISSUE TITLE
New pip release request

### ISSUE THREAD

**Issue by alexleach** [jupyterhub/autodoc-traits#5]
### Bug description
Hi, I hate to pester (and apologies if this isn't an appropriate place to put this request!), but please could you put a new release on PyPi, or create a new tag here on github? The version on PyPi doesn't work with sphinx v4, due to the removal of PyClassmember. There have been additional autodoc-traits fixes too (eg. regarding duplicate documentation of configurable properties), since the last PyPi release. I ask because I'd rather not have to either pin to a sphinx version < 4, and/or put the git+git:// ref in a docs/requirements.txt file.

Thanks, A

**Comment by minrk** [comment]
0.1.0 is published now
