### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/autodoc-traits#6]
@willingc I noted that we need to cut a release of this project for jupyterhub/oauthenticator to be able to use Sphinx 4 without installing it via a git reference. That made me motivated to setup some common JupyterHub org automation with regards to releases etc in this repo. What do you think?

### Goals

- [x] Add release automation and a RELEASE.md file
  Practically, this would be a copy-paste from another repo that publishes to PyPI.
  Example automation: https://github.com/jupyterhub/oauthenticator/blob/master/.github/workflows/publish.yml
  Example RELEASE.md: https://github.com/jupyterhub/oauthenticator/blob/master/RELEASE.md
- [x] Add badges to the README.md
  Example badges: https://github.com/jupyterhub/oauthenticator/blob/master/README.md
- [x] Initialize a CHANGELOG.md file

### Action points

- [ ] @willingc could you review the goals and action points?
- [x] @willingc could you add jupyterhubbot and perhaps another human or two (consideratio) to the associated PyPI project (https://pypi.org/project/autodoc-traits/) ?
- [ ] I'll go ahead and work towards all the goals if found to be acceptable

### Update

I missed that @minrk has opened https://github.com/jupyterhub/autodoc-traits/pull/4 already! There are some steps to take with documentation to follow that up with.

**Comment by willingc** [comment]
Hi folks, I've added @consideRatio and @minrk to the PyPI project. I've merged Min's PR. I'll need you folks to handle the rest from here or wait until next weekend. Thanks!

**Comment by minrk** [comment]
Thanks @willingc! Tested by pushing 0.1.0 (our first stable release!). Seems to have worked.

#7 adds the release, changelog, badges.

**Comment by willingc** [comment]
@consideRatio Feel free to update as you see best!
